#pragma once

#define IARM_BUS_DSMGR_NAME "DSMgr"

typedef enum _DSMgr_EventId_t {
    IARM_BUS_DSMGR_EVENT_DISPLAY_FRAMRATE_PRECHANGE,
    IARM_BUS_DSMGR_EVENT_DISPLAY_FRAMRATE_POSTCHANGE,
    IARM_BUS_DSMGR_EVENT_HDMI_IN_HOTPLUG,
    IARM_BUS_DSMGR_EVENT_HDMI_IN_SIGNAL_STATUS,
    IARM_BUS_DSMGR_EVENT_HDMI_IN_STATUS,
    IARM_BUS_DSMGR_EVENT_HDMI_IN_VIDEO_MODE_UPDATE,
    IARM_BUS_DSMGR_EVENT_HDMI_IN_ALLM_STATUS,
    IARM_BUS_DSMGR_EVENT_COMPOSITE_IN_HOTPLUG,
    IARM_BUS_DSMGR_EVENT_COMPOSITE_IN_SIGNAL_STATUS,
    IARM_BUS_DSMGR_EVENT_COMPOSITE_IN_STATUS,
} IARM_Bus_DSMgr_EventId_t;

typedef enum _dsHDRStandard_t {
    dsHDRSTANDARD_NONE = 0x0,
} dsHDRStandard_t;
