name: L0-PersistentStore

on:
  push:
    paths:
      - PersistentStore/**
      - .github/workflows/*PersistentStore*.yml
  pull_request:
    paths:
      - PersistentStore/**
      - .github/workflows/*PersistentStore*.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{github.repository}}

      - name: Install valgrind, cmake
        run: |
          sudo apt update
          sudo apt install -y valgrind cmake

      - name: Build Thunder
        working-directory: ${{github.workspace}}
        run: sh +x ${GITHUB_REPOSITORY}/.github/workflows/BuildThunder.sh

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cmake -S ${GITHUB_REPOSITORY}/PersistentStore/l0test -B build/persistentstorel0test -DCMAKE_INSTALL_PREFIX="install" -DCMAKE_CXX_FLAGS="-Wall -Werror"
          cmake --build build/persistentstorel0test --target install

      - name: Run
        working-directory: ${{github.workspace}}
        run: PATH=${PWD}/install/bin:${PATH} LD_LIBRARY_PATH=${PWD}/install/lib:${LD_LIBRARY_PATH} valgrind --tool=memcheck --log-file=valgrind_log --leak-check=yes --show-reachable=yes --track-fds=yes --fair-sched=try persistentstorel0test

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            valgrind_log
          if-no-files-found: warn
